#ifndef CONSTANT_H
#define CONSTANT_H

#define MAGIC_NUM 1314522
#define HUST_BLOCKSIZE 4096
#define HUST_N_BLOCKS 10
#define HUST_INODE_TABLE_START_IDX 4
#define HUST_ROOT_INODE_NUM 0
#define HUST_FILENAME_MAX_LEN 256
#define RESERVE_BLOCKS 2 //dummy and sb

#endif
